all: mem-exhaust socket-exhaust


mem-exhaust: mem-exhaust.c
	gcc -Wall -g mem-exhaust.c -o mem-exhaust


socket-exhaust: socket-exhaust.c
	gcc -Wall -g socket-exhaust.c -o socket-exhaust

clean:
	rm -f socket-exhaust *.o 
	rm -f mem-exhaust *.o 



